const DATABASE_NAME = '@gameplay';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;
const COLLECTION_LANGUAGE = `${DATABASE_NAME}:language`;

export {
  COLLECTION_USERS,
  COLLECTION_APPOINTMENTS,
  COLLECTION_LANGUAGE
}